# Generated by Django 5.0.6 on 2026-04-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'db_table': 'gallery_categories',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(upload_to='gallery/originals/')),
                ('thumb_small', models.ImageField(blank=True, null=True, upload_to='gallery/thumbs/small/')),
                ('thumb_medium', models.ImageField(blank=True, null=True, upload_to='gallery/thumbs/medium/')),
                ('face_embedding', models.JSONField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallerycategory')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='invitation.couplewebsite')),
            ],
            options={
                'db_table': 'gallery_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestSelfieMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie', models.ImageField(upload_to='selfies/')),
                ('selfie_embedding', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_images', models.ManyToManyField(blank=True, related_name='selfie_matches', to='gallery.galleryimage')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfie_matches', to='invitation.couplewebsite')),
            ],
            options={
                'db_table': 'guest_selfie_matches',
            },
        ),
    ]
