# Generated by Django 5.0.6 on 2026-04-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrideGroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(max_length=255)),
                ('groom_description', models.TextField(blank=True)),
                ('groom_image', models.ImageField(blank=True, null=True, upload_to='groom/')),
                ('groom_instagram', models.URLField(blank=True, null=True)),
                ('bride_name', models.CharField(max_length=255)),
                ('bride_description', models.TextField(blank=True)),
                ('bride_image', models.ImageField(blank=True, null=True, upload_to='bride/')),
                ('bride_instagram', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bride_groom',
            },
        ),
        migrations.CreateModel(
            name='BrideGroomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event/')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('location_link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='BrideGroomStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='story/')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('desc', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'stories',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='CoupleWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('royal_mughal', 'Royal Mughal'), ('kerala_trad', 'Kerala Traditional'), ('modern_minimal', 'Modern Minimal'), ('floral_pastel', 'Floral Pastel'), ('cinematic_dark', 'Cinematic Dark')], default='modern_minimal', max_length=50)),
                ('couple', models.CharField(help_text='e.g. Sunil & Priya', max_length=255)),
                ('bride_info', models.CharField(blank=True, max_length=255)),
                ('groom_info', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'couple_websites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('attendance', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YES', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invitation_rsvps',
            },
        ),
        migrations.CreateModel(
            name='Makeyourwish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wishes/')),
                ('message', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wishes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'page_visits',
            },
        ),
        migrations.CreateModel(
            name='WeddingCountdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='We Are Getting Married!', max_length=255)),
                ('event_date', models.DateTimeField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='countdown/')),
            ],
            options={
                'db_table': 'wedding_countdown',
            },
        ),
    ]
