# Generated by Django 5.0.6 on 2026-04-17 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couplewebsite',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_websites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bridegroomstory',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='invitation.couplewebsite'),
        ),
        migrations.AddField(
            model_name='bridegroomevent',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invitation.couplewebsite'),
        ),
        migrations.AddField(
            model_name='bridegroom',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bridegroom', to='invitation.couplewebsite'),
        ),
        migrations.AddField(
            model_name='invitationrsvp',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='invitation.couplewebsite'),
        ),
        migrations.AddField(
            model_name='makeyourwish',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='invitation.couplewebsite'),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='invitation.couplewebsite'),
        ),
        migrations.AddField(
            model_name='weddingcountdown',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='countdown', to='invitation.couplewebsite'),
        ),
    ]
