"""Backfill the full pre-Alembic schema (54 tables + 1 association table
that only ever existed via Base.metadata.create_all(), never a real
migration). New root of the migration chain -- migration 0001 now
depends on this instead of assuming these tables already exist.
See docs/DATABASE_CHANGES.md for the audit that found this gap.

Revision ID: 0000
Revises: (none -- new root)
Create Date: 2026-08-08 13:14:17.775709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0000'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_account_user_email'), 'account_user', ['email'], unique=True)
    op.create_index(op.f('ix_account_user_id'), 'account_user', ['id'], unique=False)
    op.create_table('gallery_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gift_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('icon_image', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vendor_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_image', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('vendor_subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price_yearly', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_packages', sa.Integer(), nullable=True),
    sa.Column('max_portfolio_images', sa.Integer(), nullable=True),
    sa.Column('featured_placement', sa.Boolean(), nullable=True),
    sa.Column('analytics_access', sa.Boolean(), nullable=True),
    sa.Column('enquiry_management', sa.Boolean(), nullable=True),
    sa.Column('custom_theme', sa.Boolean(), nullable=True),
    sa.Column('priority_support', sa.Boolean(), nullable=True),
    sa.Column('razorpay_plan_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('features_list', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier')
    )
    op.create_table('vendor_theme_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hex_color', sa.String(length=20), nullable=False),
    sa.Column('preview_image', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthday_birthdaypage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('honoree_name', sa.String(length=255), nullable=False),
    sa.Column('honoree_image', sa.String(length=200), nullable=True),
    sa.Column('cover_image', sa.String(length=200), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('theme_color', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['account_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_birthday_birthdaypage_id'), 'birthday_birthdaypage', ['id'], unique=False)
    op.create_index(op.f('ix_birthday_birthdaypage_slug'), 'birthday_birthdaypage', ['slug'], unique=True)
    op.create_table('couple_websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('couple', sa.String(length=255), nullable=False),
    sa.Column('bride_info', sa.String(length=255), nullable=True),
    sa.Column('groom_info', sa.String(length=255), nullable=True),
    sa.Column('thumbnail', sa.String(length=200), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('gallery_token', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_couple_websites_account_id'), 'couple_websites', ['account_id'], unique=False)
    op.create_index(op.f('ix_couple_websites_gallery_token'), 'couple_websites', ['gallery_token'], unique=True)
    op.create_index(op.f('ix_couple_websites_id'), 'couple_websites', ['id'], unique=False)
    op.create_index(op.f('ix_couple_websites_slug'), 'couple_websites', ['slug'], unique=True)
    op.create_table('custom_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cover_image', sa.String(length=200), nullable=True),
    sa.Column('color_theme', sa.String(length=20), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['account_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_events_id'), 'custom_events', ['id'], unique=False)
    op.create_index(op.f('ix_custom_events_owner_id'), 'custom_events', ['owner_id'], unique=False)
    op.create_table('gift_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['account_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gift_marketplace_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('buyer_name', sa.String(length=200), nullable=False),
    sa.Column('buyer_email', sa.String(length=254), nullable=False),
    sa.Column('buyer_phone', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_charge', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['account_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.create_table('gift_sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('bank_account', sa.String(length=30), nullable=True),
    sa.Column('ifsc', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['account_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('planning_budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('planned_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("event_type IN ('wedding','birthday','custom')", name='ck_planning_budget_event_type'),
    sa.ForeignKeyConstraint(['owner_id'], ['account_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planning_budget_event', 'planning_budget_items', ['event_type', 'event_id'], unique=False)
    op.create_index(op.f('ix_planning_budget_items_id'), 'planning_budget_items', ['id'], unique=False)
    op.create_index(op.f('ix_planning_budget_items_owner_id'), 'planning_budget_items', ['owner_id'], unique=False)
    op.create_table('planning_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("event_type IN ('wedding','birthday','custom')", name='ck_planning_checklist_event_type'),
    sa.ForeignKeyConstraint(['owner_id'], ['account_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planning_checklist_event', 'planning_checklist_items', ['event_type', 'event_id'], unique=False)
    op.create_index(op.f('ix_planning_checklist_items_id'), 'planning_checklist_items', ['id'], unique=False)
    op.create_index(op.f('ix_planning_checklist_items_owner_id'), 'planning_checklist_items', ['owner_id'], unique=False)
    op.create_table('planning_guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('side', sa.String(length=30), nullable=True),
    sa.Column('plus_one', sa.Boolean(), nullable=True),
    sa.Column('meal_preference', sa.String(length=50), nullable=True),
    sa.Column('rsvp', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("event_type IN ('wedding','birthday','custom')", name='ck_planning_guest_event_type'),
    sa.CheckConstraint("rsvp IN ('PENDING','ACCEPTED','DECLINED')", name='ck_planning_guest_rsvp'),
    sa.ForeignKeyConstraint(['owner_id'], ['account_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planning_guest_event', 'planning_guests', ['event_type', 'event_id'], unique=False)
    op.create_index(op.f('ix_planning_guests_id'), 'planning_guests', ['id'], unique=False)
    op.create_index(op.f('ix_planning_guests_owner_id'), 'planning_guests', ['owner_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('is_yearly', sa.Boolean(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('vendor_websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_obj_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('theme_preset_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('thumbnail', sa.String(length=200), nullable=True),
    sa.Column('cover_image', sa.String(length=200), nullable=True),
    sa.Column('theme_color', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('instagram', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_obj_id'], ['vendor_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['theme_preset_id'], ['vendor_theme_presets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_vendor_websites_id'), 'vendor_websites', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_websites_slug'), 'vendor_websites', ['slug'], unique=True)
    op.create_table('birthday_birthdaycountdown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('background_image', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['birthday_birthdaypage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id')
    )
    op.create_table('birthday_birthdayevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('location_link', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['birthday_birthdaypage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthday_birthdayrsvp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('attendance', sa.String(length=10), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('meal_preference', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['birthday_birthdaypage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthday_birthdaystory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['birthday_birthdaypage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthday_birthdaywish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relation_to_bday', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['birthday_birthdaypage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bride_groom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('groom_name', sa.String(length=255), nullable=False),
    sa.Column('groom_description', sa.Text(), nullable=True),
    sa.Column('groom_image', sa.String(length=200), nullable=True),
    sa.Column('groom_instagram', sa.String(length=200), nullable=True),
    sa.Column('bride_name', sa.String(length=255), nullable=False),
    sa.Column('bride_description', sa.Text(), nullable=True),
    sa.Column('bride_image', sa.String(length=200), nullable=True),
    sa.Column('bride_instagram', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id')
    )
    op.create_table('custom_event_budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=False),
    sa.Column('estimated', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('spent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['custom_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_event_budget_items_event_id'), 'custom_event_budget_items', ['event_id'], unique=False)
    op.create_table('custom_event_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=500), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['custom_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_event_checklist_items_event_id'), 'custom_event_checklist_items', ['event_id'], unique=False)
    op.create_table('custom_event_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('size_kb', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['custom_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_event_files_event_id'), 'custom_event_files', ['event_id'], unique=False)
    op.create_table('custom_event_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['custom_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_event_gallery_event_id'), 'custom_event_gallery', ['event_id'], unique=False)
    op.create_table('custom_event_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['custom_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_event_members_event_id'), 'custom_event_members', ['event_id'], unique=False)
    op.create_table('custom_event_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['custom_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_event_notes_event_id'), 'custom_event_notes', ['event_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('location_link', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gift_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('short_desc', sa.String(length=300), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('compare_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_cod', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['gift_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['gift_sellers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_products_id'), 'gift_products', ['id'], unique=False)
    op.create_index(op.f('ix_gift_products_slug'), 'gift_products', ['slug'], unique=True)
    op.create_table('guest_selfie_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('selfie', sa.String(length=500), nullable=False),
    sa.Column('selfie_embedding', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitation_rsvps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('attendance', sa.String(length=10), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('meal_preference', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=39), nullable=False),
    sa.Column('visited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_vendor_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('booking_status', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("event_type IN ('wedding','birthday','custom')", name='ck_planning_vendorbooking_event_type'),
    sa.ForeignKeyConstraint(['owner_id'], ['account_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_websites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_vendor_bookings_id'), 'planning_vendor_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_planning_vendor_bookings_owner_id'), 'planning_vendor_bookings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_planning_vendor_bookings_vendor_id'), 'planning_vendor_bookings', ['vendor_id'], unique=False)
    op.create_index('ix_planning_vendorbooking_event', 'planning_vendor_bookings', ['event_type', 'event_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.create_table('vendor_enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['account_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vendor_id')
    )
    op.create_table('vendor_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('max_hours', sa.Integer(), nullable=True),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('allows_custom', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_portfolio_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('icon_image', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['account_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('is_yearly', sa.Boolean(), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['vendor_subscription_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('wedding_countdown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('background_image', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id')
    )
    op.create_table('wedding_gallery_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('thumbnail', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('uploader_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wedding_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('service_note', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_websites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'vendor_id')
    )
    op.create_table('wishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relation_to_bride', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('gallery_type', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=False),
    sa.Column('thumb_small', sa.String(length=500), nullable=True),
    sa.Column('thumb_medium', sa.String(length=500), nullable=True),
    sa.Column('face_embedding', sa.JSON(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['gallery_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['account_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_images_gallery_type'), 'gallery_images', ['gallery_type'], unique=False)
    op.create_index(op.f('ix_gallery_images_id'), 'gallery_images', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_images_slug'), 'gallery_images', ['slug'], unique=True)
    op.create_table('gift_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('sender_email', sa.String(length=254), nullable=False),
    sa.Column('sender_phone', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('delivery_type', sa.String(length=10), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['gift_products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.create_table('gift_product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['gift_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gift_product_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['gift_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['account_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gift_product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['gift_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gift_scheduled_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('delivery_type', sa.String(length=10), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_qty', sa.Integer(), nullable=True),
    sa.Column('postcard_message', sa.Text(), nullable=True),
    sa.Column('postcard_template', sa.String(length=50), nullable=True),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('notes_for_team', sa.Text(), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('sender_email', sa.String(length=254), nullable=False),
    sa.Column('sender_phone', sa.String(length=20), nullable=True),
    sa.Column('sender_address_line1', sa.String(length=255), nullable=True),
    sa.Column('sender_address_line2', sa.String(length=255), nullable=True),
    sa.Column('sender_city', sa.String(length=100), nullable=True),
    sa.Column('sender_state', sa.String(length=100), nullable=True),
    sa.Column('sender_pincode', sa.String(length=10), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_email', sa.String(length=254), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('recipient_address_line1', sa.String(length=255), nullable=False),
    sa.Column('recipient_address_line2', sa.String(length=255), nullable=True),
    sa.Column('recipient_city', sa.String(length=100), nullable=False),
    sa.Column('recipient_state', sa.String(length=100), nullable=False),
    sa.Column('recipient_pincode', sa.String(length=10), nullable=False),
    sa.Column('recipient_country', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=10), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('fulfilment_status', sa.String(length=15), nullable=True),
    sa.Column('tracking_info', sa.Text(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('is_subscription', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['gift_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['account_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['couple_websites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.create_table('vendor_portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['vendor_portfolio_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_guestselfie_matched_images',
    sa.Column('guestselfie_id', sa.Integer(), nullable=False),
    sa.Column('galleryimage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['galleryimage_id'], ['gallery_images.id'], ),
    sa.ForeignKeyConstraint(['guestselfie_id'], ['guest_selfie_matches.id'], ),
    sa.PrimaryKeyConstraint('guestselfie_id', 'galleryimage_id')
    )
    op.create_table('gift_cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['gift_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['gift_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['gift_product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', 'variant_id')
    )
    op.create_table('gift_marketplace_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('variant_name', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_status', sa.String(length=10), nullable=True),
    sa.Column('tracking_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['gift_marketplace_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['gift_products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['gift_sellers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['gift_product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gift_marketplace_order_items')
    op.drop_table('gift_cart_items')
    op.drop_table('gallery_guestselfie_matched_images')
    op.drop_table('vendor_portfolio')
    op.drop_table('gift_scheduled_deliveries')
    op.drop_table('gift_product_variants')
    op.drop_table('gift_product_reviews')
    op.drop_table('gift_product_images')
    op.drop_table('gift_orders')
    op.drop_index(op.f('ix_gallery_images_slug'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_id'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_gallery_type'), table_name='gallery_images')
    op.drop_table('gallery_images')
    op.drop_table('wishes')
    op.drop_table('wedding_vendors')
    op.drop_table('wedding_gallery_photos')
    op.drop_table('wedding_countdown')
    op.drop_table('vendor_subscriptions')
    op.drop_table('vendor_reviews')
    op.drop_table('vendor_portfolio_categories')
    op.drop_table('vendor_packages')
    op.drop_table('vendor_favorites')
    op.drop_table('vendor_enquiries')
    op.drop_table('transactions')
    op.drop_table('stories')
    op.drop_index('ix_planning_vendorbooking_event', table_name='planning_vendor_bookings')
    op.drop_index(op.f('ix_planning_vendor_bookings_vendor_id'), table_name='planning_vendor_bookings')
    op.drop_index(op.f('ix_planning_vendor_bookings_owner_id'), table_name='planning_vendor_bookings')
    op.drop_index(op.f('ix_planning_vendor_bookings_id'), table_name='planning_vendor_bookings')
    op.drop_table('planning_vendor_bookings')
    op.drop_table('page_visits')
    op.drop_table('invitation_rsvps')
    op.drop_table('guest_selfie_matches')
    op.drop_index(op.f('ix_gift_products_slug'), table_name='gift_products')
    op.drop_index(op.f('ix_gift_products_id'), table_name='gift_products')
    op.drop_table('gift_products')
    op.drop_table('events')
    op.drop_index(op.f('ix_custom_event_notes_event_id'), table_name='custom_event_notes')
    op.drop_table('custom_event_notes')
    op.drop_index(op.f('ix_custom_event_members_event_id'), table_name='custom_event_members')
    op.drop_table('custom_event_members')
    op.drop_index(op.f('ix_custom_event_gallery_event_id'), table_name='custom_event_gallery')
    op.drop_table('custom_event_gallery')
    op.drop_index(op.f('ix_custom_event_files_event_id'), table_name='custom_event_files')
    op.drop_table('custom_event_files')
    op.drop_index(op.f('ix_custom_event_checklist_items_event_id'), table_name='custom_event_checklist_items')
    op.drop_table('custom_event_checklist_items')
    op.drop_index(op.f('ix_custom_event_budget_items_event_id'), table_name='custom_event_budget_items')
    op.drop_table('custom_event_budget_items')
    op.drop_table('bride_groom')
    op.drop_table('birthday_birthdaywish')
    op.drop_table('birthday_birthdaystory')
    op.drop_table('birthday_birthdayrsvp')
    op.drop_table('birthday_birthdayevent')
    op.drop_table('birthday_birthdaycountdown')
    op.drop_index(op.f('ix_vendor_websites_slug'), table_name='vendor_websites')
    op.drop_index(op.f('ix_vendor_websites_id'), table_name='vendor_websites')
    op.drop_table('vendor_websites')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_planning_guests_owner_id'), table_name='planning_guests')
    op.drop_index(op.f('ix_planning_guests_id'), table_name='planning_guests')
    op.drop_index('ix_planning_guest_event', table_name='planning_guests')
    op.drop_table('planning_guests')
    op.drop_index(op.f('ix_planning_checklist_items_owner_id'), table_name='planning_checklist_items')
    op.drop_index(op.f('ix_planning_checklist_items_id'), table_name='planning_checklist_items')
    op.drop_index('ix_planning_checklist_event', table_name='planning_checklist_items')
    op.drop_table('planning_checklist_items')
    op.drop_index(op.f('ix_planning_budget_items_owner_id'), table_name='planning_budget_items')
    op.drop_index(op.f('ix_planning_budget_items_id'), table_name='planning_budget_items')
    op.drop_index('ix_planning_budget_event', table_name='planning_budget_items')
    op.drop_table('planning_budget_items')
    op.drop_table('gift_sellers')
    op.drop_table('gift_marketplace_orders')
    op.drop_table('gift_carts')
    op.drop_index(op.f('ix_custom_events_owner_id'), table_name='custom_events')
    op.drop_index(op.f('ix_custom_events_id'), table_name='custom_events')
    op.drop_table('custom_events')
    op.drop_index(op.f('ix_couple_websites_slug'), table_name='couple_websites')
    op.drop_index(op.f('ix_couple_websites_id'), table_name='couple_websites')
    op.drop_index(op.f('ix_couple_websites_gallery_token'), table_name='couple_websites')
    op.drop_index(op.f('ix_couple_websites_account_id'), table_name='couple_websites')
    op.drop_table('couple_websites')
    op.drop_index(op.f('ix_birthday_birthdaypage_slug'), table_name='birthday_birthdaypage')
    op.drop_index(op.f('ix_birthday_birthdaypage_id'), table_name='birthday_birthdaypage')
    op.drop_table('birthday_birthdaypage')
    op.drop_table('vendor_theme_presets')
    op.drop_table('vendor_subscription_plans')
    op.drop_table('vendor_categories')
    op.drop_table('gift_categories')
    op.drop_table('gallery_categories')
    op.drop_index(op.f('ix_account_user_id'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_email'), table_name='account_user')
    op.drop_table('account_user')
    # ### end Alembic commands ###
